### ISSUE TITLE
일부 상황에서 추첨 확정 시 보상이 2배로 적용되는 문제

### ISSUE THREAD

**Issue by HotoRas** [smh0505/PlatinumKey#25]
발생 조건 모름.

**Comment by smh0505** [comment]
해당 킹시보기를 보고 확인해본 결과 정상작동임이 확인되었습니다.
- 보상이 2배로 적용되는 조건: 일반 주사위 더블 스택(`isDouble`: boolean)이 true로 남아있을 것
- 킹시보기를 돌려본 결과, 보상이 2배로 들어온 추첨 직전에 굴렸던 **일반 주사위**가 더블이었습니다.
